name: Jess Huffman
favicon: null
layout_spectrum: 0.19939790666103363
typography_spectrum: 0.9269238929264247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9726218872237951
  lightness: 0.9740441953763366
  saturation: 0.684185222024098
  rhythmicContrast: 0.04813027638010681
purpose: []
