name: Jess Huffman
favicon: null
layout_spectrum: 0.19939790666103363
typography_spectrum: 0.8504
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1812f'
    - '#4d2c16'
    - '#ac6129'
    - '#e9975e'
    - '#bb8a65'
  brandStrength: 0.9726218872237951
  lightness: 0.9740441953763366
  saturation: 0.684185222024098
  rhythmicContrast: 0.04813027638010681
purpose: []
